customhost = "database-1.c7fbjsirefag.us-east-1.rds.amazonaws.com"
customuser = "awsuser"
custompass = "Bait3273"
customdb = "employee"
custombucket = "tancheekean-employee"
customregion = "us-east-1"
